name: helath_care
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  date_format: ^2.0.4
  intl: ^0.17.0
  http: ^0.13.3
  fluttertoast: ^8.0.8
  contained_tab_bar_view: ^0.8.0
  shared_preferences: ^2.0.8
  flutter_easyloading: ^3.0.3
  pin_code_fields: ^7.3.0
  flutter_time_picker_spinner: ^2.0.0
  google_maps_flutter: ^2.0.11
  dart_ipify: ^1.1.1
  buttons_tabbar: ^1.3.1
  device_info: ^0.4.1+2
  firebase_messaging: ^10.0.8
  firebase_core: ^1.7.0
  firebase_analytics: ^8.3.3
  flutter_rating_bar: ^4.0.0
  image_picker: ^0.8.4+4
  path: ^1.8.0
  flutter_html: ^0.8.2
  location: ^2.5.4
  provider: ^6.0.1
  syncfusion_flutter_signaturepad: ^19.3.54
  path_provider: ^2.0.7
  month_picker_dialog: ^0.4.0
  flutter_image_compress: ^1.1.0
  image_gallery_saver: ^1.2.2
  ntp: ^2.0.0
  geolocator: ^5.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter



  # rules and activating additional ones.
  flutter_lints: ^1.0.0
# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/


  uses-material-design: true


